export const COLORS = {
  background: "#F8FAFF",
  card: "#FFFFFF",
  border: "#E4E8F0",
  transparent: "transparent",
  primary: "#5546DF",
  primaryDark: "#4536D2",
  text: "#101322",
  muted: "#515B73",
  subtle: "#7A8499",
  track: "#E8EAF1",
  success: "#139B6C",
  shadow: "#101828",
  moodVeryHappy: "#CFF8DF",
  moodVeryHappySoft: "#ECFFF3",
  moodHappy: "#D5FBDD",
  moodHappySoft: "#F0FFF3",
  moodNeutral: "#E2D8FF",
  moodNeutralSoft: "#F4F0FF",
  moodSad: "#FFF1BC",
  moodSadSoft: "#FFF9E6",
  moodStressed: "#FFD6C8",
  moodStressedSoft: "#FFF0EA",
  iconPurpleSoft: "#EEE9FF",
};
